---
- ros_topic_name: "clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "joint_states"
  gz_topic_name: "/world/map/model/iris/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "odometry"
  gz_topic_name: "/model/iris/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "gz/tf"
  gz_topic_name: "/model/iris/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "gz/tf_static"
  gz_topic_name: "/model/iris/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "camera/image"
  gz_topic_name: "/world/map/model/iris/link/pitch_link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "camera/camera_info"
  gz_topic_name: "/world/map/model/iris/link/pitch_link/sensor/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "air_pressure"
  gz_topic_name: "/world/map/model/iris/link/base_link/sensor/air_pressure_sensor/air_pressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS

# - ros_topic_name: "air_speed"
#   gz_topic_name: "/world/map/model/iris/link/base_link/sensor/air_speed_sensor/air_speed"
#   ros_type_name: "geometry_msgs/msg/Vector3Stamped"
#   gz_type_name: "gz.msgs.AirSpeedSensor"
#   direction: GZ_TO_ROS

# - ros_topic_name: "altimeter"
#   gz_topic_name: "/world/map/model/iris/link/base_link/sensor/altimeter_sensor/altimeter"
#   ros_type_name: "geometry_msgs/msg/Vector3Stamped"
#   gz_type_name: "gz.msgs.Altimeter"
#   direction: GZ_TO_ROS

- ros_topic_name: "imu"
  gz_topic_name: "/world/map/model/iris/link/imu_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "magnetometer"
  gz_topic_name: "/world/map/model/iris/link/base_link/sensor/magnetometer_sensor/magnetometer"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "navsat"
  gz_topic_name: "/world/map/model/iris/link/base_link/sensor/navsat_sensor/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

- ros_topic_name: "battery"
  gz_topic_name: "/model/iris/battery/linear_battery/state"
  ros_type_name: "sensor_msgs/msg/BatteryState"
  gz_type_name: "gz.msgs.BatteryState"
  direction: GZ_TO_ROS
